import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
  richColors
  toastOptions={{
    classNames: {
      error: "!text-gray-900 !bg-red-50 !border-red-200",
      success: "!text-gray-900 !bg-green-50 !border-green-200",
      warning: "!text-gray-900 !bg-yellow-50 !border-yellow-200",
      info: "!text-gray-900 !bg-blue-50 !border-blue-200",
      description: "!text-gray-500",
    },
  }}
/>
      </body>
    </html>
  );
}
